# backend/estrategia/coletor_dinamico.pyi
from typing import Any, Dict, List

class ColetorDeAtivos:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def carregar_ativos(self) -> List[Dict[str, Any]]: ...
    # outros helpers possíveis
    def buscar_ativo(self, codigo: str) -> Dict[str, Any] | None: ...
