# backend/api/binance_cliente.pyi
from typing import Any, Dict, Optional
import pandas as pd

class ClienteBinance:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def obter_klines_historicos(self, par: str, intervalo: str = "1m", limite: int = 500) -> "pd.DataFrame": ...
    # caso possua outros métodos úteis:
    def obter_saldo(self) -> Dict[str, Any]: ...
    def fechar(self) -> None: ...
